/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.store.ui;

import java.awt.BorderLayout;
import java.util.Map;
import java.util.HashMap;
/**
 *
 * @author chenjingjun
 */
public class LoadingFrame extends javax.swing.JFrame{
    
    public static LoadingFrame instance = new LoadingFrame();
    
    /**
     * Creates new form LodingFrame
     */
    private int progress = 0;
    private final Map<Integer, Integer> coutMap = new HashMap<>();
    private MainLoading loadingPanel;
    
    private LoadingFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.loadingPanel = new MainLoading();
    }
    
    public void init(){
        loadingPanel.start(() -> {
            dispose();
        });
        setLayout(new BorderLayout());  
        this.add(loadingPanel, BorderLayout.CENTER); 
        setVisible(true);
    }
    
    public void updateCount(int type, int value){
         loadingPanel.updateCount(type, value);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
