/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.store.ui;

import com.store.data.user.UserManager;
import com.store.ui.common.ConfirmDialog;
import com.store.ui.common.table.TableTextComboBox;
import java.util.Collection;
/**
 *
 * @author chenjingjun
 */
public class LoginFrame extends javax.swing.JFrame{
    
    public static LoginFrame instance = new LoginFrame();
    
    private Runnable runnable;
    
    private LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void initUser(Collection<String> users){
        TableTextComboBox comboBox = (TableTextComboBox)txt_account;
        comboBox.changeItems(users.toArray());
    }
    
    public MainLoading getLoading() {
        return loading;
    }

    private void invokeCallback() {
        String account = txt_account.getText().trim();
        String password = txt_password.getText().trim();
        if (UserManager.isUser(account)) {
            if(UserManager.login(account, password)){
                OK();
            }
            else{
                txt_password.setText("");
                ConfirmDialog.show("密码错误");
            }
        }
        else{
            txt_account.setText("");
            ConfirmDialog.show("用户不存在");
        }
    }
    
    private void OK(){
        jButton1.setEnabled(false);
        runnable.run();
    }
    
    public void initOk(Runnable runnable){
        this.runnable = runnable;
        setVisible(true);
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField ();
        jButton1 = new javax.swing.JButton();
        loading = new com.store.ui.MainLoading();
        jLabel2 = new javax.swing.JLabel();
        txt_account = new com.store.ui.common.table.TableTextComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("登陆系统");
        setBackground(new java.awt.Color(255, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFont(new java.awt.Font("楷体", 0, 10)); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("楷体", 1, 14)); // NOI18N
        jLabel1.setText("密码：");

        jButton1.setText("确定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1onBtnConfirm(evt);
            }
        });

        loading.setBorder(null);

        jLabel2.setFont(new java.awt.Font("楷体", 1, 14)); // NOI18N
        jLabel2.setText("账号：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loading, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_account, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1onBtnConfirm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1onBtnConfirm
        // TODO add your handling code here:
        invokeCallback();
    }//GEN-LAST:event_jButton1onBtnConfirm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.store.ui.MainLoading loading;
    private javax.swing.JTextField txt_account;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables

}
