/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.store.ui;

import com.store.ui.common.ConfirmDialog;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author chenjingjun
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final MainFrame instance = new MainFrame();
    
    private TabUIType current; 
    
    public static MainFrame getInstance() {
        return instance;
    }
   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_container = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setType(java.awt.Window.Type.POPUP);

        tab_container.setFont(new java.awt.Font("楷体", 1, 14)); // NOI18N
        tab_container.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_container, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     */
    public void beforeInit(MainLoading loading) {
        loading.initCount(MainLoading.TAB_UI, TabUIType.values().length);
    }
    
    /**
     */
    public void onOnit(MainLoading loading) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        instance.initTabUI(loading);
        /* Create and display the form */
    }
    
    public void finish(){
        java.awt.EventQueue.invokeLater(() -> {
            instance.setTitle("海生建材水暖商店库存工具【个人定制版】");
            instance.setVisible(true);
            current = TabUIType.getTabUIType(tab_container.getSelectedIndex());;
        });
    }
    
    /**
     * 初始化TABUI
     * @param loading 
     */
    protected void initTabUI(MainLoading loading){
        for(TabUIType uIType : TabUIType.values()){
            tab_container.addTab(uIType.name, (Component)uIType.component);
            loading.updateCount(MainLoading.TAB_UI, 1);
            uIType.component.initOne();
            uIType.component.initUI(false);
        }
        tab_container.addChangeListener((ChangeEvent e) -> {
            int index = tab_container.getSelectedIndex();
            TabUIType uIType = TabUIType.getTabUIType(index);
            if(current == uIType){
                return;
            }
            else if(current.getComponent().siwtchEnanble()){
                uIType.component.initUI(uIType.initUI);
                current = uIType;
            }
            else{
                tab_container.setSelectedIndex(current.id);
                ConfirmDialog.show("未完成操作，不能切换页签");
            }
            ((JPanel)current.component).updateUI();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tab_container;
    // End of variables declaration//GEN-END:variables
}
